### ISSUE TITLE
Add debug option to merge2 

### ISSUE THREAD

**Issue by laldecol** [economic-research/open-ado#61]
merge 2 only looks for csv files when merging. Other analogous commands, like psave, use csv when building and dta when debugging. 

We can solve this by adding a debug option to merge2, which directs it to look for a .dta file and not declare file dependencies when global $debug=="debug"

**Comment by andres-jurado** [comment]
Wouldn't that be the regular merge command? We wrote merge2 to merge CSV
instead of having to read a CSV file and then save it to DTA.


*José Andrés Jurado*
Economics Student
